#!/usr/bin/env bash
# Configures and deploys trace "lite" on Render, after the service exists
# (Render dashboard -> New -> Blueprint -> this repository).
#
#   deploy/deploy-render.sh
#
# Reads accounts from .env.deploy and model keys from .env, both local only.
# Creates the private Hugging Face dataset that holds uploaded files, sets
# every environment variable on the Render service, starts a deploy and waits
# for it. Safe to run again; it replaces the service's variables each time.
set -euo pipefail
cd "$(dirname "$0")/.."

# Read as KEY=value text, not sourced as shell: a Neon URL carries "&".
load() {
  python3 - "$@" <<'PY'
import re, shlex, sys
for name in sys.argv[1:]:
    for line in open(name):
        m = re.match(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$", line)
        if not m:
            continue
        value = m.group(2).strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        print(f"export {m.group(1)}={shlex.quote(value)}")
PY
}
eval "$(load .env .env.deploy)"

missing=()
for name in RENDER_API_KEY HF_TOKEN HF_USERNAME NEON_DATABASE_URL QDRANT_CLOUD_URL QDRANT_CLOUD_API_KEY GROQ_API_KEY GEMINI_API_KEY; do
  [ -n "${!name:-}" ] || missing+=("$name")
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "fill these in .env.deploy (or .env) first: ${missing[*]}" >&2
  exit 1
fi

render=https://api.render.com/v1
rauth=(-H "Authorization: Bearer $RENDER_API_KEY" -H "Accept: application/json")
storage="$HF_USERNAME/${HF_STORAGE_NAME:-trace-storage}"

echo "==> finding the Render service"
service=$(curl -fsS "${rauth[@]}" "$render/services?name=${RENDER_SERVICE_NAME:-trace}&limit=20" | python3 -c '
import json, sys
items = [entry["service"] for entry in json.load(sys.stdin)]
if not items:
    sys.exit("no Render service named trace yet: create it with New -> Blueprint first")
service = items[0]
print(service["id"], service["serviceDetails"].get("url") or "")')
service_id=${service%% *}
service_url=${service#* }
echo "    $service_id  $service_url"

echo "==> private storage dataset $storage"
status=$(curl -s -o /tmp/trace-ds.json -w '%{http_code}' -H "Authorization: Bearer $HF_TOKEN" -H 'content-type: application/json' \
  -X POST https://huggingface.co/api/repos/create \
  -d "{\"type\":\"dataset\",\"name\":\"${storage#*/}\",\"private\":true}")
case "$status" in
  200|201) echo "    created" ;;
  409) echo "    already exists" ;;
  *) echo "could not create the dataset ($status): $(cat /tmp/trace-ds.json)" >&2; exit 1 ;;
esac

# Generated once and kept, so a redeploy does not sign everybody out.
if [ -z "${RENDER_JWT_SECRET:-}" ]; then
  RENDER_JWT_SECRET=$(openssl rand -hex 32)
  printf '\n# Generated by deploy-render.sh; keeps sessions valid across deploys.\nRENDER_JWT_SECRET=%s\n' "$RENDER_JWT_SECRET" >> .env.deploy
fi

echo "==> setting environment variables"
export SERVICE_URL="$service_url" STORAGE_REPO="$storage" RENDER_JWT_SECRET
python3 - <<'PY' > /tmp/trace-env.json
import json, os
e = os.environ.get
pairs = {
    "DATABASE_URL": e("NEON_DATABASE_URL"),
    "QDRANT_URL": e("QDRANT_CLOUD_URL"),
    "QDRANT_API_KEY": e("QDRANT_CLOUD_API_KEY"),
    "JWT_SECRET": e("RENDER_JWT_SECRET"),
    "HF_TOKEN": e("HF_TOKEN"),
    "HF_STORAGE_REPO": e("STORAGE_REPO"),
    "GROQ_API_KEY": e("GROQ_API_KEY"),
    "GEMINI_API_KEY": e("GEMINI_API_KEY"),
    "CORS_ORIGIN": e("SERVICE_URL"),
    "SIGNUP_ALLOWLIST": e("SIGNUP_ALLOWLIST", ""),
}
for name in ("GROQ_MODEL", "GROQ_FAST_MODEL", "GROQ_RPM", "GEMINI_MODEL", "GEMINI_FAST_MODEL",
             "GEMINI_CAPTION_MODEL", "SUFFICIENCY_MIN_SCORE", "SUFFICIENCY_MIN_RELEVANT_CHUNKS"):
    if e(name):
        pairs[name] = e(name)
print(json.dumps([{"key": k, "value": v or ""} for k, v in pairs.items()]))
PY
curl -fsS -o /dev/null "${rauth[@]}" -H 'content-type: application/json' \
  -X PUT "$render/services/$service_id/env-vars" --data @/tmp/trace-env.json
rm -f /tmp/trace-env.json /tmp/trace-ds.json
echo "    done"

echo "==> deploying (the first build takes about 10 minutes)"
deploy_id=$(curl -fsS "${rauth[@]}" -H 'content-type: application/json' -X POST "$render/services/$service_id/deploys" -d '{}' \
  | python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])')
for _ in $(seq 1 90); do
  state=$(curl -fsS "${rauth[@]}" "$render/services/$service_id/deploys/$deploy_id" | python3 -c 'import json,sys; print(json.load(sys.stdin)["status"])')
  case "$state" in
    live) break ;;
    build_failed|update_failed|canceled|deactivated)
      echo "deploy $state; see the logs in the Render dashboard" >&2; exit 1 ;;
  esac
  sleep 20
done
echo "    $state"

if curl -fsS "$service_url/api/healthz" >/dev/null 2>&1; then
  echo
  echo "trace is live at $service_url"
else
  echo "deployed, but $service_url/api/healthz is not answering yet; give it a minute" >&2
fi
