#!/usr/bin/env bash
# Deploys trace to a free Hugging Face Space, with Postgres on Neon, vectors
# on Qdrant Cloud, and uploaded files in a private Hugging Face dataset.
#
#   deploy/deploy-hf.sh
#
# Reads the account details from .env.deploy and the model keys from .env,
# both on this machine only. Safe to run again: it updates the same Space.
# Hugging Face then builds the image (about 20 minutes the first time).
set -euo pipefail
cd "$(dirname "$0")/.."

[ -f .env.deploy ] || { echo ".env.deploy is missing" >&2; exit 1; }
set -a
# shellcheck disable=SC1091
. ./.env
# shellcheck disable=SC1091
. ./.env.deploy
set +a

missing=()
for name in HF_TOKEN HF_USERNAME NEON_DATABASE_URL QDRANT_CLOUD_URL QDRANT_CLOUD_API_KEY GROQ_API_KEY; do
  [ -n "${!name:-}" ] || missing+=("$name")
done
if [ ${#missing[@]} -gt 0 ]; then
  echo "fill these in .env.deploy (or .env) first: ${missing[*]}" >&2
  exit 1
fi

space="$HF_USERNAME/${HF_SPACE_NAME:-trace}"
storage="$HF_USERNAME/${HF_STORAGE_NAME:-trace-storage}"
# A Space is served at <owner>-<name>.hf.space, lowercased, with dots and
# underscores turned into hyphens.
host="$(echo "${space/\//-}" | tr '[:upper:]' '[:lower:]' | tr '._' '--').hf.space"
api=https://huggingface.co/api
auth=(-H "Authorization: Bearer $HF_TOKEN")

# The session-signing secret is generated once and kept, so redeploying does
# not sign everybody out.
if [ -z "${HF_JWT_SECRET:-}" ]; then
  HF_JWT_SECRET=$(openssl rand -hex 32)
  printf '\n# Generated by deploy-hf.sh; keeps sessions valid across deploys.\nHF_JWT_SECRET=%s\n' "$HF_JWT_SECRET" >> .env.deploy
fi

create() { # type name private
  local status
  status=$(curl -s -o /tmp/trace-hf-create.json -w '%{http_code}' "${auth[@]}" -H 'content-type: application/json' \
    -X POST "$api/repos/create" -d "$4")
  case "$status" in
    200|201) echo "    created $2" ;;
    409) echo "    $2 already exists" ;;
    *) echo "could not create $2 ($status): $(cat /tmp/trace-hf-create.json)" >&2; exit 1 ;;
  esac
}

echo "==> Hugging Face repositories"
create space "$space" false "{\"type\":\"space\",\"name\":\"${space#*/}\",\"sdk\":\"docker\",\"private\":false}"
create dataset "$storage" true "{\"type\":\"dataset\",\"name\":\"${storage#*/}\",\"private\":true}"

setting() { # kind(secrets|variables) key value
  curl -fsS -o /dev/null "${auth[@]}" -H 'content-type: application/json' \
    -X POST "$api/spaces/$space/$1" \
    -d "$(KEY="$2" VALUE="$3" python3 -c 'import json,os; print(json.dumps({"key": os.environ["KEY"], "value": os.environ["VALUE"]}))')"
}

echo "==> Space settings"
# Secrets: never shown back, not even to the owner.
setting secrets DATABASE_URL "$NEON_DATABASE_URL"
setting secrets QDRANT_URL "$QDRANT_CLOUD_URL"
setting secrets QDRANT_API_KEY "$QDRANT_CLOUD_API_KEY"
setting secrets JWT_SECRET "$HF_JWT_SECRET"
setting secrets HF_TOKEN "$HF_TOKEN"
setting secrets GROQ_API_KEY "$GROQ_API_KEY"
setting secrets GEMINI_API_KEY "${GEMINI_API_KEY:-}"
# Variables: settings that are not secret.
setting variables HF_STORAGE_REPO "$storage"
setting variables CORS_ORIGIN "https://$host"
setting variables SIGNUP_ALLOWLIST "${SIGNUP_ALLOWLIST:-}"
for name in GROQ_MODEL GROQ_FAST_MODEL GROQ_RPM GEMINI_MODEL GEMINI_FAST_MODEL GEMINI_CAPTION_MODEL \
            WEB_SEARCH_PROVIDER SUFFICIENCY_MIN_SCORE SUFFICIENCY_MIN_RELEVANT_CHUNKS; do
  [ -n "${!name:-}" ] && setting variables "$name" "${!name}"
done
echo "    done"

echo "==> pushing the code"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
rsync -a \
  --exclude .git --exclude node_modules --exclude '**/node_modules' --exclude '**/dist' \
  --exclude .turbo --exclude '**/__pycache__' --exclude '.env*' --exclude data \
  --exclude 'eval/reports' --exclude '*.docx' \
  ./ "$work/"
cp hf/Dockerfile "$work/Dockerfile"
# The Space's card: its metadata block, then the project's own README.
{
  cat <<'EOF'
---
title: trace
emoji: 📄
colorFrom: red
colorTo: gray
sdk: docker
app_port: 7860
pinned: false
short_description: Answers from your own documents, with citations that resolve
---

EOF
  cat README.md
} > "$work/README.md"

(
  cd "$work"
  git init -q -b main
  git add -A
  git -c user.name="$HF_USERNAME" -c user.email="$HF_USERNAME@users.noreply.huggingface.co" \
    commit -q -m "Deploy trace"
  git push -q --force "https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$space" main
)

echo
echo "Pushed. Hugging Face is building it now (about 20 minutes the first time)."
echo "  build log:  https://huggingface.co/spaces/$space?logs=build"
echo "  the app:    https://$host"
echo "Open the app at the second address, not inside the huggingface.co page:"
echo "signing in needs the page to be its own site, not a frame."
